### PR TITLE
feat (Date-handling): Store dates in UTC. (#807)

### PR DESCRIPTION
**Pull request by jafin**
**EDIT**

* Ensure all dates are converted to UTC before persisting by configuring DateTime properties with ValueConverters to convert to UTC.
* Observed that responses in JSON will have the 'Z' suffix noting the times are in UTC Kind. Front end client appears to render in local time.
 * EF Migration step to convert existing data to UTC added.

Relates to #807

### CODE REVIEW

**Comment by rnwood** [comment]
Thanks for the contribution again @jafin. 
Is it possible to change this bit so that it will work with both old and new values without migration of the data?

`       v => DateTime.SpecifyKind(v, DateTimeKind.Utc));`

What `Kind` does EF return the old and new values with? I'm guessing `Unknown` and `Utc`, so should be possible to differentiate and correctly convert the old values to UTC here?

**Comment by jafin** [comment]
@rnwood ,  The value when converted to UTC is represented the same in the column.
Before: `2021-07-26 22:34:24.0402814`
After: `2021-07-26 12:47:35.3737624`

No indication of timezone in that column

From what I read, SQLite with EFCore doesn't appear to support storing of Timezone offset unless you implement a [DateTImeOffsetToBinaryConverter](https://nitratine.net/blog/post/a-warning-for-ef-cores-datetimeoffsettobinaryconverter/) to persist the value.

Rather than adjusting the data type of the column, I made the option to begin storing values as UTC from this moment on.

So to your question, I don't see a way to detect the old/new data.

One way I see to maintain this would be a migration script on launch.  This is assuming you run the migration in the correct timezone, then it could update existing data to UTC, and then continue from that point on storing UTC values to the DB.

If that works for you as a fix, I can take a look at doing a migration script for this PR.   I didn't initially since I use smtp4dev with ephemeral data, I suspect others may use it for more longer term storage..  :-)

**Comment by rnwood** [comment]
OK that make sense. As you suggested, I think we just need to add an EF DB migration to convert the existing data to UTC.

**Comment by jafin** [comment]
I just saw new test broke on cross platform run. Just reading on https://stackoverflow.com/questions/41566395/timezoneinfo-in-net-core-when-hosting-on-unix-nginx  .  I've adjusted the test to fallback to a deserialized version of the TZ.  I don't have docker running so I'll see how it goes through the CI build.

**Pull request merged**
