### PR TITLE
Move search to server side 

### PR DESCRIPTION
**Pull request by rnwood**
and deal with the consequences - notifications need to be retrieved separately.

### CODE REVIEW

**Comment by rnwood** [comment]
One of the current side effects is that (since SQLite doesn't support it with defaults) the case insensitivity will only apply to characters in the ASCII range.

I'd like to resolve this before merging if possible. Since it will affect many smtp4dev international users.

**Comment by smchristensen** [comment]
That's the direction I was going while looking at this.  Since the search is server side and the base query returns the entire message, you could use something like the Boyer-Moore search algorithm to search on the data field of the message.  This could effectively search the body of the message as well, right?  If I'm wrong feel free to chastise. :)

**Comment by rnwood** [comment]
> That's the direction I was going while looking at this. Since the search is server side and the base query returns the entire message, you could use something like the Boyer-Moore search algorithm to search on the data field of the message. This could effectively search the body of the message as well, right? If I'm wrong feel free to chastise. :)

No chastising needed! I would definitely love to add search that is searching the message content as well as the subject/to/from that it's currently doing. I'm going to log this as a separate feature though so I can get this bug fix out.

For now I've merged the server side search that is equivalent to the current client side search but without the paging drawback.

**Comment by smchristensen** [comment]
Thank you for this!

**Pull request merged**
